### ISSUE TITLE
Don't use python-shell-interpreter to find python executable

### ISSUE THREAD

**Issue by snarisi** [emacs-lsp/lsp-python-ms#11]
If a user's config changes `python-shell-interpreter` to `ipython`, for example, [these lines](https://github.com/andrew-christianson/lsp-python-ms/blob/master/lsp-python-ms.el#L61-L72) will give an unexpected result. I believe `(executable-find "python")` should give what you want. 

Can open a PR if this makes sense.

**Comment by andrew-christianson** [comment]
Makes sense to me. Pyenv environments are also effected by this e.g. I set python-shell-interpreter to python, but create a virtualenv without python, unexpected things will indeed result.

**Comment by andrew-christianson** [comment]
Merged #12

**Comment by forrestchang** [comment]
How to configure server to other python versions?  It seems the default version is system version which is python 2.7. And use virtualenv in Emacs to set Python to 3.7 is not work for lsp-python-ms.

**Comment by ztlevi** [comment]
Yeah, vote for python 3 issue. It's better to have a second custom variable like `lsp-python-ms-python-executable` if someone uses ipython as default.

**Comment by foltra** [comment]
I have the same issue as @forrestchang . I have projects under pyenv/pipenv,  more or less working before #12 changes. I would activate the environment then with `python-shell-interpreter` set to the right value,  restart backend with`lsp-workspace-restart` and everything would be fine after.

**Comment by seagle0128** [comment]
@foltra The commit https://github.com/emacs-lsp/lsp-python-ms/commit/006bfc79451d176a75e6f1d2b3f480c0b12ca636 has been added `lsp-python-executable-cmd` variable.

**Comment by foltra** [comment]
I missed to look at the update, Thanks! @seagle0128
