### ISSUE TITLE
Always picks pyls, never mspyls

### ISSUE THREAD

**Issue by XO39** [emacs-lsp/lsp-python-ms#115]
I've been using pyls all along up till today, I removed pyls and installed mspyls as mentions in the readme file, but every time I open a python file, it still picks pyls with an error (because I deleted python-language-server):

`Server pyls:xxxxx status:starting exited with status exit. Do you want to restart it? (y or n)`

 Even when I only have these settings in my python-mode-related file:
``` elisp
(require 'lsp-python-ms)
(setq lsp-python-ms-auto-install-server t)
(add-hook 'python-mode-hook #'lsp)
```

**Comment by seagle0128** [comment]
Did you restart Emacs? And please confirm pyls is removed completely. I couldn't reproduce this issue.

**Comment by XO39** [comment]
Yes, I did restart Emacs, and I did completely removed the pyls. Are there any modes in Emacs that conflict with lsp-python-ms? I just don't know why lsp-mode would pick pyls when pyls is not installed? Is there any settings in Emacs for that?

**Comment by XO39** [comment]
OK, I got it working, there were a leftover pyls executable in the pyenv path belongs to an older version of python. Sorry for the trouble. Closing this.
