### ISSUE TITLE
All symbols in file called "Variable" in completions

### ISSUE THREAD

**Issue by jsigman** [emacs-lsp/lsp-python-ms#116]
This is very snappy and almost a great replacement for `pyls`, however there are still some ways that I need to fix my configuration of this package.

Right now, all symbols in the python file I'm editing show as "Variable". This happens whether I use `capf` backend of `company-lsp` backend to company. Clearly, the server can see that `Foo` is a class, and not a variable, because it outputs information. See screenshots below.

<img width="626" alt="Screen Shot 2020-07-23 at 10 21 36 PM" src="https://user-images.githubusercontent.com/2373529/88355638-53223b80-cd33-11ea-8ac2-b4778d952777.png">

<img width="628" alt="Screen Shot 2020-07-23 at 10 21 02 PM" src="https://user-images.githubusercontent.com/2373529/88355640-55849580-cd33-11ea-8ad9-8dbd49dc3f58.png">

**Comment by jsigman** [comment]
It is clear that the server and company-backend are capable of identifying methods, classes, etc. It just never assigns these labels for the source files that I'm editing...

![Screen Shot 2020-07-24 at 10 38 27 AM](https://user-images.githubusercontent.com/2373529/88402988-e0987680-cd99-11ea-8a24-e9c7e21000b3.png)

**Comment by seagle0128** [comment]
I think it's the behavior of mspyls itself.

**Comment by jsigman** [comment]
Right... do you know why that would be, is mypyls misconfigured? In VSCode, it would correctly identify these things

**Comment by seagle0128** [comment]
Did you try with VSCode? It's same in my env.

**Comment by jsigman** [comment]
In this simple example, VSCode is capable of distinguishing different entities. classes, variables, and methods

![Screen Shot 2020-07-24 at 11 14 55 AM](https://user-images.githubusercontent.com/2373529/88406754-1f7cfb00-cd9f-11ea-8807-6650f80f9f03.png)

![Screen Shot 2020-07-24 at 11 15 03 AM](https://user-images.githubusercontent.com/2373529/88406763-21df5500-cd9f-11ea-81e8-ace2dbd7efdb.png)

![Screen Shot 2020-07-24 at 11 15 12 AM](https://user-images.githubusercontent.com/2373529/88406772-2441af00-cd9f-11ea-9b73-4187d7267f03.png)

**Comment by jsigman** [comment]
This is quite a strange issue, and seems to be quite a breaking issue. Generally, I want intelligent completions from the source files I'm editing, and not merely the packages in my virtual environment. I don't know why it would treat these two things differently

**Comment by seagle0128** [comment]
It may be a configuration issue but not very sure. I am looking into it.

BTW,  we are working on the new client https://github.com/emacs-lsp/lsp-pyright, which is a better choice in future.

**Comment by jsigman** [comment]
Awesome. Thanks for all that you do. I think that actually it's still quite workable how it is. I'll look into pyright.
