### ISSUE TITLE
LSP never reach "started"?

### ISSUE THREAD

**Issue by alxchk** [emacs-lsp/lsp-python-ms#13]
I'm trying to use lsp-python-ms with latest lsp-mode and have next behavior:
1. On first (open .py file in new folder) run I have in messages
```
LSP :: Connected to [mspyls:833946 status:starting].
LSP :: Object reference not set to an instance of an object.
```
and nothing in mspyls buffers.

LSP logs says that mspyls was choosen, and status line has `LSP[mspyls:PID status:starting]`.

2. On second run I don't have
```
LSP :: Object reference not set to an instance of an object.
```
message, rest is the same.

Describe session:
```
[-] /tmp/tt/
 `-[-] mspyls:833946 status:starting
    |-[-] Buffers
    |  |-[+] test.py
    |  `-[+] nil
    `-[+] Capabilities
```

**Comment by alxchk** [comment]
Issue was with MS Python server from master. Looks like latest tagged version works

**Comment by vv111y** [comment]
I have this problem now, even building from current master branch. 
(The package in the AUR for arch users is definitely out of date fyi).
It refuses to start. I was hoping it is busy building autocomplete information, but CPU use is low.
Maybe this should be re-opened.

What tagged version did you use? Maybe they reintroduced the problem.

**Comment by alxchk** [comment]
I have this on master. I build ms lsp server from git

**Comment by twlz0ne** [comment]
Same here.

- macOS 10.12.6
- Python 3.6.5
- Emacs Nightly 2019-05-25 (commit: 0597c1b94e5206e980865c6513e923280a3c3ce1)
- mspyls 2019-06-12 (commit: fc1a2c6bdaee5f6b53be80426d6de25e80df9edc)
- lsp-python-ms-20190421.2332

**Comment by vv111y** [comment]
Seems to be working, just pulled and rebuilt the server.  
- mspyls commit 53de3cd9f7ac88c9fb600401b59cc24783c1c79e
- 4.19.42-1-MANJARO
- Python 3.6.7
- lsp-python-ms 20190614.814

I'll try it out more today.

**Comment by seagle0128** [comment]
Please try the latest version.

**Comment by seagle0128** [comment]
Any update? @alxchk @vv111y @twlz0ne

**Comment by vv111y** [comment]
working on my end

**Comment by seagle0128** [comment]
Then I will close it. Thank you!
