### ISSUE TITLE
how to trigger

### ISSUE THREAD

**Issue by CDitzel** [emacs-lsp/lsp-python-ms#14]
I installed .net and the microsoft dependencies according to the instructions. then I included the small elisp snippet into my init file and Emacs starts without any errors. 

However, i do not get any completion or hints whatsoever. I used ubuntu.18.04-x64. 

M-x lsp does not yield any results, so I figure there is something off here...

Can anyone help? how do I trigger the lsp?

edit: so I set ensure from nil to t and then after reloading Emacs states

> Error (use-package): Failed to install lsp-python-ms: Package ‘lsp-python-ms-’
is unavailable

what to do?

**Comment by sehnsucht13** [comment]
Hello CDitzel! This package is not on melpa. The reason why it is not triggering is because it is not installed. I am not the author and I had the same issue. What you have to do is clone this repository somewhere in your .emacs.d folder so emacs can find it. After that you need to copy and paste the snippet provided(which it seems like you have already done) and set the paths to the binary for the language server.

**Comment by CDitzel** [comment]
I did that, but how can I make sure that it finds the cloned package? In the provided snippet, the two bottom lines seem to be optional and I dont see any reference to the package whatsoever.

Also, is the LSP package a complete replacement for elpy, company and the likes and if not, how does it interact with them? should I disable the other packages in order to make these one here function properly?

**Comment by CDitzel** [comment]
ok so i put the following in my config file

```
(use-package lsp-python-ms
      :demand
      :load-path "~/.emacs.d/git-repos/lsp-python-ms"
      :ensure nil
      :hook (python-mode . lsp)
      :config
      ;; for dev build of language server
      (setq lsp-python-ms-dir
            (expand-file-name "~/.emacs.d/git-repos/python-language-server/output/bin/Release/"))
      ;; for executable of language server
      (setq lsp-python-ms-executable
            "~/.emacs.d/git-repos/python-language-server/output/bin/Release/ubuntu.18.04-x64/publish/Microsoft.Python.LanguageServer"))

    (provide 'init-python)

    (use-package lsp-mode
      :ensure t
      :commands lsp
      :hook
      (python-mode . lsp)
      :init
      (setq lsp-prefer-flymake nil)
      (add-to-list 'exec-path "/home/ditzel/anaconda3/envs/py37/bin")
      :init
      (add-hook 'prog-major-mode #'lsp-prog-major-mode-enable))

    (use-package lsp-ui
      :ensure t
      :commands lsp-ui-mode)

    (provide 'init-lsp-mode)

    (use-package company-lsp
      :ensure t
      :init
      (push 'company-lsp company-backends))
```

is that correct ?

- Why dont I need [lsp-python](https://github.com/emacs-lsp/lsp-python) for that matter?

- what to do, if I get "unresolved import .." ?

thank you for your help

**Comment by yyoncho** [comment]
remove

> (add-hook 'prog-major-mode #'lsp-prog-major-mode-enable)

> :init
>      (push 'company-lsp company-backends

**Comment by CDitzel** [comment]
thank you, whenever I start Emacs and launch a project file in python I see 

![1550248777](https://user-images.githubusercontent.com/22954412/52870838-081cf580-3149-11e9-93db-63e93ab9efa9.png)

and the parsing hints remain until I click somewhere. is that the ordinary behaviour?

**Comment by andrew-christianson** [comment]
@CDitzel yes, that's expected - AFAIK that's the language server reporting the message, and lsp-ui is just displaying it on the sideline.

**Comment by CDitzel** [comment]
thank you, is the LSP support a substitute for all the other python packages/minor modes, or are some of them still recommended aside from LSP? And do I also need [LSP-python](https://github.com/emacs-lsp/lsp-python)? It doesnt seem to be in Melpa anyway...

**Comment by CDitzel** [comment]
I think I gotit running, however, I am not sure that the behaviour I have, is the default one. For instance, if completion is triggeres, it just yields me completely random suggestions, cf. the image below

![1550742024](https://user-images.githubusercontent.com/22954412/53159097-76d4d580-35c5-11e9-974d-7229781d2f13.png)

Is there something wrong here?

Also, if I usually work in Anaconda, do I need to inform lsp-python-ms of that?

thank you in advance

**Comment by jakejx** [comment]
Not sure if its related, but my company completions are also not filtered based on the current substring.
![image](https://user-images.githubusercontent.com/5763900/53579851-50aac900-3bb5-11e9-8001-42ec8b624dd7.png)

**Comment by yyoncho** [comment]
@njunxuan @CDitzel take a look at https://github.com/tigersoldier/company-lsp/issues/79

**Comment by CDitzel** [comment]
> Not sure if its related, but my company completions are also not filtered based on the current substring.
> ![image](https://user-images.githubusercontent.com/5763900/53579851-50aac900-3bb5-11e9-8001-42ec8b624dd7.png)

would you mind sharing the portions of your emacs config with me, so that I can understand the basic steps to set up the lsp? maybe I did something wrong...

**Comment by jakejx** [comment]
> > Not sure if its related, but my company completions are also not filtered based on the current substring.
> > ![image](https://user-images.githubusercontent.com/5763900/53579851-50aac900-3bb5-11e9-8001-42ec8b624dd7.png)
> 
> would you mind sharing the portions of your emacs config with me, so that I can understand the basic steps to set up the lsp? maybe I did something wrong...

I'm using spacemacs so I don't think my config would be applicable!

**Comment by andrew-christianson** [comment]
@CDitzel can this issue be closed?  Let me know if you need more help getting everything configured.

**Comment by CDitzel** [comment]
lsp does not work for me. the engine renders my emacs effectively non-functional due to massive delay and strange behaviour. But this can be closed for now. I reverted back to anaconda mode -.-

**Comment by andrew-christianson** [comment]
sorry to hear - both lsp-mode and the python language server are under rapid and active development so hopefully the performance will improve sufficiently in the future.
