### ISSUE TITLE
lsp doesn't recognize parsed lsp-python-ms download link

### ISSUE THREAD

**Issue by avhn** [emacs-lsp/lsp-python-ms#143]
Can't see any servers listed by the lsp as below at initial launch:

```
Unable to find installed server supporting this file. The following servers could be installed automatically: 
```
then, `lsp--client, nil` warning comes. 

**lsp-python-ms-latest-nupkg-url** is giving the legit install url for the os. (macOS)
**lsp-python-ms--install-server** seems like it should work.

Same code was working before(quite a while ago), probably because of lsp specification itself changed. Is this about`lsp-register-client`?

**Comment by seagle0128** [comment]
Please check your network and retry `M-x lsp-python-ms-update-server`. I am pretty sure it's working on macOS.

**Comment by avhn** [comment]
Anyone experiencing issues about *lsp-python-ms-auto-install-server* not working anymore for some reason, the proposed solution above works.
