### ISSUE TITLE
Undefined variable in nested lambda

### ISSUE THREAD

**Issue by SimonHauguel** [emacs-lsp/lsp-python-ms#151]
Code to reproduce
```py
_ = lambda x : lambda _ : x
```
I get an `Undefined variable: 'x'` error.
This error seems to occur for all variables that have a depth level `>= 2`

In case the variable is defined somewhere else than in the arguments of a lambda, there are no errors
```py
y = None
_ = lambda _ : lambda _ : y # all's good
```

**Comment by seagle0128** [comment]
Is this issue for mspyls itself?

**Comment by SimonHauguel** [comment]
This problem seems to appear only from my emacs instance of ms py lsp.
That's why i came here, but you're right, i'm probably in the wrong place. Sorry about that.
