### ISSUE TITLE
Failed to run lsp-goto-type-definition and lsp-goto-implementation.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-lsp/lsp-python-ms#155]
I test the `lsp-python-ms` with the following python code snippet:
```python
import numpy as np
from numpy import pi, sin

a = np.array([1], dtype=bool)
if np.invert(a) == ~a:
    print('ok')
```
I put the point at the following position of the above code snippet (denoted by `|`):

`if np.in|vert(a) == ~a:`

Then I do the following testings:

`M-x lsp-goto-type-definition` failed with the following message:

```
if: The connected server(s) does not support method textDocument/typeDefinition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

`M-x lsp-goto-implementation` failed with the following message:

```
if: The connected server(s) does not support method textDocument/implementation.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```
I would like to see information similar to that provided by `pycharm`, as shown below:

![image](https://user-images.githubusercontent.com/11155854/137619512-674e0eda-7564-4e76-af86-04a194ebeb8e.png)
![image](https://user-images.githubusercontent.com/11155854/137619524-a0b584a3-1627-4612-ab1f-05ec1af67d55.png)

Any hints for this problem?

PS. I encountered the same problem with `python-lsp-server` as reported [here](https://github.com/python-lsp/python-lsp-server/issues/97).

Regards,
HZ

**Comment by seagle0128** [comment]
As the messages, the connected server(mspyls) does not support method textDocument/typeDefinition and textDocument/implementation. 

If you just see more docs for the current symbols, just use `lsp-ui-doc` of `lsp-mode`.

**Comment by hongyi-zhao** [comment]
If the connected server does not support the requested method, `lsp-ui` will fail too:
`C-x lsp-ui-peek-find-implementation RET`
```
if: The connected server(s) does not support method textDocument/implementation.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

**Comment by seagle0128** [comment]
We can do nothing if so. Please file an issue for mspyls, but it's deprecated.

**Comment by hongyi-zhao** [comment]
> We can do nothing if so. Please file an issue for mspyls, but it's deprecated.

Then which one is recommended now?

**Comment by seagle0128** [comment]
Please use [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright/) instead.

**Comment by hongyi-zhao** [comment]
> Please use [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright/) instead.

Does [lsp-pyright](https://github.com/emacs-lsp/lsp-pyright/) have the features discussed here?

**Comment by seagle0128** [comment]
@hongyi-zhao I think you don't understand. The features you mentioned depend on LSP server, while not the clients. You should ask `pyright` and `mspyls`.
