### ISSUE TITLE
CI Badge isn't displayed

### ISSUE THREAD

**Issue by ghost** [emacs-lsp/lsp-python-ms#158]
If you go to [lsp python ms](https://emacs-lsp.github.io/lsp-python-ms/) there is text instead of the CI badge.

![image](https://user-images.githubusercontent.com/27790087/163879398-5bfc76dc-c2d6-4351-b25e-f737bc847edf.png)

**Comment by seagle0128** [comment]
It's displayed correctly in my env.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/140797/163953375-8faf6d3e-7f8f-413c-b55d-96be48a3f21f.png">
