### ISSUE TITLE
Warning (lsp-mode): Unknown method: python/reportProgress

### ISSUE THREAD

**Issue by rememberYou** [emacs-lsp/lsp-python-ms#16]
Hello,

First of all, a big thank you for creating this package.

Recently, I decided to give a try to your package and when opening a Python file, my `*Warnings*` buffer is filled with this kind of Warnings:
![2019-03-07_09 49 45](https://user-images.githubusercontent.com/6253527/53943912-799ff200-40be-11e9-90a6-96df41240a06.png)

I don't know if this is an issue that concerns `lsp-python-ms` or `lsp-mode` in general. However, since I only found this issue with`lsp-python-ms`, I post this issue here.

If it helps, here is the configuration I use:
```
(use-package lsp-mode
  :hook ((c-mode c++-mode python-mode) . lsp)
  :custom
  (lsp-prefer-flymake nil)
  (lsp-session-file (expand-file-name (format "%s/emacs/lsp-session-v1" xdg-data))))

(use-package lsp-ui)
(use-package company-lsp)

(use-package lsp-python-ms
  :demand
  :load-path "~/.emacs.d/elisp/lsp-python-ms"
  :custom
  (lsp-python-ms-dir (expand-file-name "~/.emacs.d/elisp/python-language-server/output/bin/Release/"))
  (lsp-python-ms-executable "~/.emacs.d/elisp/python-language-server/output/bin/Release/linux-x64/publish/Microsoft.Python.LanguageServer"))
```

For the installation of [python-language-server](https://github.com/Microsoft/python-language-server), I did exactly as [README.org](https://github.com/andrew-christianson/lsp-python-ms/blob/master/README.org) recommends. Except that for the [Runtime ID Catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog) (`-r flag`), I used `linux-64` since I'm on Arch Linux.
```
uname -a
Linux ThinkPad 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux
```

Since when loading a python file, I do have a message from `lsp-mode` warning me that it has found the `mspyls` LSP client and that it works, I don't know where these warnings can come from.
```
LSP :: Connected to [mspyls:2148].
```

**NOTE:** ignoring these warnings is simply impossible, from the moment I open the Python file, the `*Warnings*` buffer floods with these warnings.

**Comment by andrew-christianson** [comment]
Yup just noticed this when I updated the language server this morning.  I'll push a fix shortly
