### ISSUE TITLE
Extra paths.

### ISSUE THREAD

**Issue by CMLL** [emacs-lsp/lsp-python-ms#19]
In the vscode implementation with the LS, they take into account a variable named "python.autoComplete.extraPaths" that seem to indicate the server to search for those included paths when performing the analysis in case you have extra libraries you want to check for auto completion. 

Is there any way to pass that sort of value to the lsp using the emacs client?

**Comment by andrew-christianson** [comment]
Sure, it's easy to extend, just dropped in @ #20 .  Let me know if that works & I'll merge it in

**Comment by CMLL** [comment]
Awesome, let me try and I'll report back.

**Comment by CMLL** [comment]
It worked perfectly, thanks a lot.
