### ISSUE TITLE
Unable to find Microsoft.Python.LanguageServer

### ISSUE THREAD

**Issue by Compro-Prasad** [emacs-lsp/lsp-python-ms#24]
**ls output/bin/Release/publish/Microsoft.Python.LanguageServer.***
```
output/bin/Release/publish/Microsoft.Python.LanguageServer.deps.json
output/bin/Release/publish/Microsoft.Python.LanguageServer.dll
output/bin/Release/publish/Microsoft.Python.LanguageServer.pdb
output/bin/Release/publish/Microsoft.Python.LanguageServer.runtimeconfig.json
```

**Comment by andrew-christianson** [comment]
`dotnet publish -r <platform-arch>` should place its artifacts in `output/bin/Release/publish/<platform-arch>/`.  What OS are you on?  How did you build the language server?

**Comment by Compro-Prasad** [comment]
I am on Arch Linux.

**Comment by samspills** [comment]
Did you run with the correct runtime specified? Did the publish command return any errors? I am on manjaro (which is just beginners arch haha) and publishing worked for me. I published with:
`dotnet publish -c Release -r linux-x64 `
and the executable is generated at the expected path: 
`output/bin/Release/linux-x64/publish/Microsoft.Python.LanguageServer`

**Comment by Compro-Prasad** [comment]
Thanks. It worked.
