### ISSUE TITLE
Language server not starting when opening a single file

### ISSUE THREAD

**Issue by vn-ki** [emacs-lsp/lsp-python-ms#25]
When I open a directory using dired, the lanugage server works correctly.

But when I open a single using `emacs file.py`, the language does not start by saying `No LSP for python-mode`.

**Comment by seblemaguer** [comment]
Can you try to eval `(require 'lsp-python-ms)` and then restart `lsp` manually? On my side it works this way. The call to use-package is not sufficient. I don't know why yet and I didn't have the time to investigate.

**Comment by prittjam** [comment]
I am also having this problem.

**Comment by braineo** [comment]
because it is not a project?

related discussion

https://github.com/emacs-lsp-legacy/lsp-python/issues/28

**Comment by seblemaguer** [comment]
On my side it was because I forgot the `:demand`.

**Comment by ianyepan** [comment]
Yes, you do need to add `:demand` if you are using `use-package`, otherwise you would have to call the `lsp` command manually.

However, I have always wondered how come `lsp-java` does not require the `:demand` keyword while `lsp-python-ms` does?

**Comment by seagle0128** [comment]
`:demand` is not necessary if `use-package-always-defer` is nil. The point is the mspyls client is registered while loading `lsp-python-ms` package.

It seems it can be closed now. Please reopen if you have further questions.
