### ISSUE TITLE
How to get formatting and linting?

### ISSUE THREAD

**Issue by vn-ki** [emacs-lsp/lsp-python-ms#26]
I don't get formatting nor linting capabilities.

I do have pylint and yapf installed.

**Comment by seagle0128** [comment]
MS pyls doesn't have such capabilities, neither does `lsp-python-ms`.

You can set `lsp-python-ms-errors`, `lsp-python-ms-warnings`, `lsp-python-ms-information` and `lsp-python-ms-disabled` for diagnostics messages. `lsp-ui-flycheck` displays via `flycheck`.

Please refer to https://github.com/Microsoft/python-language-server#linting-options-diagnostics for more details.

I recommend to use [yapfify](https://github.com/JorisE/yapfify) to format the buffer. 

Regarding linting, you can use `flycheck` + `pylint` or `flake8`.
