### ISSUE TITLE
[Feature Request] Setup server automatically

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-python-ms#33]
This is inspired by `lsp-java`, and will make `lsp-python-ms` out-of-box.

Actually I've implemented the feature in `Centaur Emacs`. I am not sure if you are interested in. If you think it does make sense, you can merge into the upstream. I'd like to help here even submit the PR , but it needs to make big changes for the design and needs your advice.

Please refer to  https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-lsp.el#L126.

**Comment by yyoncho** [comment]
I was about to file this issue too. 

> I'd like to help here even submit the PR , but it needs to make big changes for the design and needs your advice.

I am fine with such PR. Let me know about the design changes. If they are part of lsp-mode I could help with that. 

Also, if you are interested I am looking for more collaborators for the project. It looks like there is a lot of stuff that can be done to improve the project. We need also someone to monitor the MS PYLS dev process and adjust the project accordingly.

**Comment by seagle0128** [comment]
Actually this was discussed for a several days in https://emacs-china.org/t/lsp-python-ms-vs-pyls/9611. Some developers are able to help on this, I think. I also can help when avilable.
