### ISSUE TITLE
Maybe custom python executable variable rather `(executable-find "python")`

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-python-ms#36]
Thanks for this fantastic plugin catches up ms python lsp.

But I have some python3 issue because it's hard coded
[here](https://github.com/emacs-lsp/lsp-python-ms/blob/master/lsp-python-ms.el#L98) and we are not
able to utilize the python3. And flycheck keeps popping message showing requires python 3.x. 

Moreover, not sure if the current solution is able to use virtual env's since we have to manually pick
python executable somehow in VScode.

What do you think?

**Comment by yyoncho** [comment]
Take a look here - https://github.com/emacs-lsp/lsp-python-ms/pull/35/ . It has a configuration for python executable. If this is not sufficient I am open for smarter suggestion eventually implementation.

**Comment by ztlevi** [comment]
Great, my bad didn't check the PRs. I will close this.
