### ISSUE TITLE
Lisp error: (wrong-number-of-arguments #<subr encode-time> 1)

### ISSUE THREAD

**Issue by failable** [emacs-lsp/lsp-python-ms#39]
After updated to the latest version of `lsp-python-ms`, the following error happens

    Debugger entered--Lisp error: (wrong-number-of-arguments #<subr encode-time> 1)
      encode-time((19 3 1 16 2 2019 6 nil 0))
      #f(compiled-function (blob) #<bytecode 0x47120545>)((Blob nil (Name nil "Python-Language-Server-osx-x64.0.1.80.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.1.80.nupkg") (Properties nil (Last-Modified nil "Sat, 16 Feb 2019 01:03:19 GMT") (Etag nil "0x8D693AA8A2A9741") (Content-Length nil "29680349") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "PQboldiTQhvtBw7Pfkej8g==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))))
      mapcar(#f(compiled-function (blob) #<bytecode 0x47120545>) ((Blob nil (Name nil "Python-Language-Server-osx-x64.0.1.80.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.1.80.nupkg") (Properties nil (Last-Modified nil "Sat, 16 Feb 2019 01:03:19 GMT") (Etag nil "0x8D693AA8A2A9741") (Content-Length nil "29680349") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "PQboldiTQhvtBw7Pfkej8g==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))) (Blob nil (Name nil "Python-Language-Server-osx-x64.0.2.82.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.82.nupkg") (Properties nil (Last-Modified nil "Fri, 17 May 2019 16:03:17 GMT") (Etag nil "0x8D6DAE12D11E5F1") (Content-Length nil "29805519") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "/4oBhh+mnCtNh1fCIgV/pA==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))) (Blob nil (Name nil "Python-Language-Server-osx-x64.0.2.86.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.86.nupkg") (Properties nil (Last-Modified nil "Thu, 23 May 2019 19:41:04 GMT") (Etag nil "0x8D6DFB697EA18B8") (Content-Length nil "29810201") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "GE+mpcJ1QmtnbWp4FnXuWw==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))) (Blob nil (Name nil "Python-Language-Server-osx-x64.0.2.87.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.87.nupkg") (Properties nil (Last-Modified nil "Wed, 29 May 2019 16:40:02 GMT") (Etag nil "0x8D6E4544C13E92E") (Content-Length nil "29811094") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "+ztai6wZMzlcP83ChYjwqA==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))) (Blob nil (Name nil "Python-Language-Server-osx-x64.0.2.96.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.2.96.nupkg") (Properties nil (Last-Modified nil "Thu, 06 Jun 2019 20:43:14 GMT") (Etag nil "0x8D6EABF992C5A43") (Content-Length nil "29810778") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "6DeAeBBOiYJFk3HgWr5Y+g==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked"))) (Blob nil (Name nil "Python-Language-Server-osx-x64.0.3.20.nupkg") (Url nil "https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.3.20.nupkg") (Properties nil (Last-Modified nil "Mon, 24 Jun 2019 20:02:02 GMT") (Etag nil "0x8D6F8DED2AA0D2A") (Content-Length nil "29820701") (Content-Type nil "application/octet-stream") (Content-Encoding nil) (Content-Language nil) (Content-MD5 nil "os6J180GbCd9EPtmvioeew==") (Cache-Control nil) (BlobType nil "BlockBlob") (LeaseStatus nil "unlocked")))))
      lsp-python-ms-latest-nupkg-url("stable")
      lsp-python-ms-setup()
      lsp-python-ms--command-string()
      lsp-resolve-final-function(lsp-python-ms--command-string)
      #f(compiled-function () #<bytecode 0x471fb01d>)()
      #f(compiled-function (client) #<bytecode 0x4105d1a5>)(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x471208e1>) :test\? #f(compiled-function () #<bytecode 0x471fb01d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x471fb029> :request-handlers #<hash-table equal 0/65 0x471fb301> :response-handlers #<hash-table eql 0/65 0x471fb321> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x471fb741> :action-handlers #<hash-table equal 0/65 0x471fbb41> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x471208d1>) :remote? nil :completion-in-comments? nil))
      -filter(#f(compiled-function (client) #<bytecode 0x4105d1a5>) (#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x471208e1>) :test\? #f(compiled-function () #<bytecode 0x471fb01d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x471fb029> :request-handlers #<hash-table equal 0/65 0x471fb301> :response-handlers #<hash-table eql 0/65 0x471fb321> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x471fb741> :action-handlers #<hash-table equal 0/65 0x471fbb41> :major-modes (python-mode) :activation-fn nil :priority 1 :server-id mspyls :multi-root nil :initialization-options lsp-python-ms--extra-init-params :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x471208d1>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40e95845>) :test\? #f(compiled-function () #<bytecode 0x40e9585d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40e95869> :request-handlers #<hash-table equal 0/65 0x471fa63d> :response-handlers #<hash-table eql 0/65 0x471fa65d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f676c1> :action-handlers #<hash-table equal 0/65 0x40ea27c1> :major-modes (python-mode) :activation-fn nil :priority -1 :server-id pyls :multi-root nil :initialization-options nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x40e957cd>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40e95809>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40ea1585>) :test\? #f(compiled-function () #<bytecode 0x40ea159d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x40ea15a9> :request-handlers #<hash-table equal 0/65 0x40e8ee41> :response-handlers #<hash-table eql 0/65 0x40e80b41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40e80ee1> :action-handlers #<hash-table equal 1/65 0x40ea15c9> :major-modes (rust-mode rustic-mode) :activation-fn nil :priority -1 :server-id rls :multi-root nil :initialization-options ((omitInitBuild . t) (cmdRun . t)) :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x40fc18ad>) :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40fc18c5>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40fc22ad>) :test\? #f(compiled-function () #<bytecode 0x40fc22c5>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40fc22d1> :request-handlers #<hash-table equal 0/65 0x40fc25a9> :response-handlers #<hash-table eql 0/65 0x40fc264d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40fb5dc1> :action-handlers #<hash-table equal 0/65 0x40fb6201> :major-modes (ruby-mode enh-ruby-mode) :activation-fn nil :priority -1 :server-id ruby-ls :multi-root t :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40e812b1>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40faab89>) :test\? #f(compiled-function () #<bytecode 0x40faaba1>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40faabad> :request-handlers #<hash-table equal 0/65 0x40faaddd> :response-handlers #<hash-table eql 0/65 0x40fab961> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40fab981> :action-handlers #<hash-table equal 0/65 0x40fabdc1> :major-modes (html-mode sgml-mode mhtml-mode web-mode) :activation-fn nil :priority -4 :server-id html-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (w) #<bytecode 0x40faaa75>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40fac2a9>) :test\? #f(compiled-function () #<bytecode 0x40fac2c1>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by Vue but content not available") :notification-handlers #<hash-table equal 0/65 0x40fac2cd> :request-handlers #<hash-table equal 0/65 0x40fac5a5> :response-handlers #<hash-table eql 0/65 0x40fac5c5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40faa9c1> :action-handlers #<hash-table equal 0/65 0x40fbb5c1> :major-modes nil :activation-fn #f(compiled-function (filename mode) #<bytecode 0x40fbcb15>) :priority -1 :server-id vls :multi-root t :initialization-options #f(compiled-function () #<bytecode 0x40fbcb31>) :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40fbcb51>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40fbb1e9>) :test\? #f(compiled-function () #<bytecode 0x40fa06fd>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 2/65 0x40fa0709> :request-handlers #<hash-table equal 0/65 0x40fa0a01> :response-handlers #<hash-table eql 0/65 0x40fa0cd9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40fa0d7d> :action-handlers #<hash-table equal 0/65 0x40fa11c1> :major-modes (php-mode) :activation-fn nil :priority -1 :server-id iph :multi-root t :initialization-options #f(compiled-function () #<bytecode 0x40fbb1a9>) :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f8aa71>) :test\? #f(compiled-function () #<bytecode 0x40f8aa89>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f8ad6d> :request-handlers #<hash-table equal 0/65 0x40f8ad8d> :response-handlers #<hash-table eql 0/65 0x40f8b1c1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f8b5c1> :action-handlers #<hash-table equal 1/65 0x40f8aa95> :major-modes (css-mode less-mode less-css-mode sass-mode scss-mode) :activation-fn nil :priority -1 :server-id css-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f90f49>) :test\? #f(compiled-function () #<bytecode 0x40f90ea9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f90f6d> :request-handlers #<hash-table equal 0/65 0x40f9119d> :response-handlers #<hash-table eql 0/65 0x40f911bd> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f911dd> :action-handlers #<hash-table equal 0/65 0x40f919c1> :major-modes nil :activation-fn #f(compiled-function (file-name mode) #<bytecode 0x40f90ed5>) :priority 0 :server-id xmlls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40f90eed>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f91fad>) :test\? #f(compiled-function () #<bytecode 0x40f91fc5>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f91fd1> :request-handlers #<hash-table equal 0/65 0x40f9217d> :response-handlers #<hash-table eql 0/65 0x40f9219d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f921bd> :action-handlers #<hash-table equal 0/65 0x40f921dd> :major-modes (go-mode) :activation-fn nil :priority 0 :server-id gopls :multi-root nil :initialization-options nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x40f91e3d>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f97a5d>) :test\? #f(compiled-function () #<bytecode 0x40f97a75>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f97a81> :request-handlers #<hash-table equal 0/65 0x40f97d59> :response-handlers #<hash-table eql 0/65 0x40f98035> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f9832d> :action-handlers #<hash-table equal 0/65 0x40f9855d> :major-modes (go-mode) :activation-fn nil :priority -1 :server-id go-bingo :multi-root nil :initialization-options lsp-clients-go--make-init-options :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x40f979dd>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f98961>) :test\? #f(compiled-function () #<bytecode 0x40f98979>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f98985> :request-handlers #<hash-table equal 0/65 0x40f989a5> :response-handlers #<hash-table eql 0/65 0x40f989c5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f991c1> :action-handlers #<hash-table equal 0/65 0x40f98dc1> :major-modes (go-mode) :activation-fn nil :priority -2 :server-id go-ls :multi-root nil :initialization-options lsp-clients-go--make-init-options :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x40f979ed>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f9b2b1>) :test\? #f(compiled-function () #<bytecode 0x40f9b2c9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f9b5ad> :request-handlers #<hash-table equal 0/65 0x40f9b5cd> :response-handlers #<hash-table eql 0/65 0x40f831c1> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x40f9b2d5> :action-handlers #<hash-table equal 0/65 0x40f835c1> :major-modes (clojure-mode clojurec-mode clojurescript-mode) :activation-fn nil :priority 0 :server-id clojure-lsp :multi-root nil :initialization-options (:dependency-scheme "jar") :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f87a9d>) :test\? #f(compiled-function () #<bytecode 0x40f87ab5>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f87ac1> :request-handlers #<hash-table equal 0/65 0x40f87d99> :response-handlers #<hash-table eql 0/65 0x40f87db9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f87dd9> :action-handlers #<hash-table equal 0/65 0x40f7afc1> :major-modes (dart-mode) :activation-fn nil :priority -2 :server-id dart_language_server :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f7b6b9>) :test\? #f(compiled-function () #<bytecode 0x40f7b6cd>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f7b6d9> :request-handlers #<hash-table equal 0/65 0x40f7b77d> :response-handlers #<hash-table eql 0/65 0x40f7bbc1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f7b79d> :action-handlers #<hash-table equal 0/65 0x40f7b7bd> :major-modes (dart-mode) :activation-fn nil :priority -1 :server-id dart_analysis_server :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f7c7e5>) :test\? #f(compiled-function () #<bytecode 0x40f79add>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f79ae9> :request-handlers #<hash-table equal 0/65 0x40f79c95> :response-handlers #<hash-table eql 0/65 0x40f79cb5> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f79cd5> :action-handlers #<hash-table equal 0/65 0x40f73ac1> :major-modes (elm-mode) :activation-fn nil :priority -1 :server-id elm-ls :multi-root nil :initialization-options lsp-clients-elm--make-init-options :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f89b2d>) :test\? #f(compiled-function () #<bytecode 0x40f89b45>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f89b51> :request-handlers #<hash-table equal 0/65 0x40f89d81> :response-handlers #<hash-table eql 0/65 0x40f89da1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f89dc1> :action-handlers #<hash-table equal 0/65 0x40f630c1> :major-modes (scala-mode) :activation-fn nil :priority -1 :server-id metals :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn #f(compiled-function (workspace) #<bytecode 0x40f89ad5>) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f63645>) :test\? #f(compiled-function () #<bytecode 0x40f6365d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 3/65 0x40f63669> :request-handlers #<hash-table equal 0/65 0x40f63899> :response-handlers #<hash-table eql 0/65 0x40f638b9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f638d9> :action-handlers #<hash-table equal 0/65 0x40f5b4c1> :major-modes (fsharp-mode) :activation-fn nil :priority 0 :server-id fsac :multi-root nil :initialization-options lsp-fsharp--make-init-options :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5b9b1>) :test\? #f(compiled-function () #<bytecode 0x40f5b9c9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f5b9d5> :request-handlers #<hash-table equal 0/65 0x40f5bcad> :response-handlers #<hash-table eql 0/65 0x40f5bccd> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f6bfc1> :action-handlers #<hash-table equal 0/65 0x40f5c0c1> :major-modes (sh-mode) :activation-fn nil :priority -1 :server-id bash-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5c4f1>) :test\? #f(compiled-function () #<bytecode 0x40f5c539>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f5c545> :request-handlers #<hash-table equal 0/65 0x40f5c81d> :response-handlers #<hash-table eql 0/65 0x40f5c8c1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f5ccc1> :action-handlers #<hash-table equal 0/65 0x40f5d101> :major-modes (groovy-mode) :activation-fn nil :priority -1 :server-id groovy-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5d6ad>) :test\? #f(compiled-function () #<bytecode 0x40f5d6c5>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but content not available") :notification-handlers #<hash-table equal 0/65 0x40f5d6d1> :request-handlers #<hash-table equal 0/65 0x40f5d87d> :response-handlers #<hash-table eql 0/65 0x40f5d89d> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f5d8bd> :action-handlers #<hash-table equal 0/65 0x40f5d8dd> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -3 :server-id jsts-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5e0ed>) :test\? #f(compiled-function () #<bytecode 0x40f5dce5>)) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but content not available") :notification-handlers #<hash-table equal 0/65 0x40f5e5a9> :request-handlers #<hash-table equal 0/65 0x40f5e881> :response-handlers #<hash-table eql 0/65 0x40f5e8a1> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f5ecc1> :action-handlers #<hash-table equal 0/65 0x40f5f0c1> :major-modes nil :activation-fn lsp-typescript-javascript-tsx-jsx-activate-p :priority -2 :server-id ts-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5f52d>) :test\? #f(compiled-function () #<bytecode 0x40f5f541>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f5f54d> :request-handlers #<hash-table equal 0/65 0x40f5f825> :response-handlers #<hash-table eql 0/65 0x40f5f8c9> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4aa41> :action-handlers #<hash-table equal 0/65 0x40f4ae81> :major-modes nil :activation-fn lsp-clients-flow-activate-p :priority -1 :server-id flow-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f5f8e9>) :test\? #f(compiled-function () #<bytecode 0x40f4ae6d>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f4b1b5> :request-handlers #<hash-table equal 0/65 0x40f4b259> :response-handlers #<hash-table eql 0/65 0x40f4b641> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4ba81> :action-handlers #<hash-table equal 0/65 0x40f4bd59> :major-modes (php-mode) :activation-fn nil :priority -2 :server-id php-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f4aa6d>) :test\? #f(compiled-function () #<bytecode 0x40f4be61>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f4c0b5> :request-handlers #<hash-table equal 0/65 0x40f4c3ad> :response-handlers #<hash-table eql 0/65 0x40f4c5dd> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4c5fd> :action-handlers #<hash-table equal 0/65 0x40f4c61d> :major-modes (reason-mode caml-mode tuareg-mode) :activation-fn nil :priority -1 :server-id ocaml-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f4c669>) :test\? #f(compiled-function () #<bytecode 0x40f4cfd9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f4cfe5> :request-handlers #<hash-table equal 0/65 0x40f4d215> :response-handlers #<hash-table eql 0/65 0x40f4d235> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4d255> :action-handlers #<hash-table equal 0/65 0x40f4e241> :major-modes (c-mode c++-mode objc-mode) :activation-fn nil :priority -1 :server-id clangd :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f4e74d>) :test\? #f(compiled-function () #<bytecode 0x40f4e761>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f4e76d> :request-handlers #<hash-table equal 0/65 0x40f4ea45> :response-handlers #<hash-table eql 0/65 0x40f4ed39> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4f031> :action-handlers #<hash-table equal 0/65 0x40f4f329> :major-modes (elixir-mode) :activation-fn nil :priority -1 :server-id elixir-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn (closure (t) (workspace) (puthash "textDocumentSync" (let ((ht-temp ...)) (ht-set! ht-temp "save" t) (ht-set! ht-temp "change" 2) ht-temp) (progn (or (and ... t) (signal ... ...)) (aref workspace 2)))) :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f4f65d>) :test\? #f(compiled-function () #<bytecode 0x40f4f671>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f4f6ad> :request-handlers #<hash-table equal 0/65 0x40f4f985> :response-handlers #<hash-table eql 0/65 0x40f4fa29> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f4fa49> :action-handlers #<hash-table equal 0/65 0x40f4fe41> :major-modes (f90-mode fortran-mode) :activation-fn nil :priority -1 :server-id fortls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f505ad>) :test\? #f(compiled-function () #<bytecode 0x40f505c1>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x40f505cd> :request-handlers #<hash-table equal 0/65 0x40f508b5> :response-handlers #<hash-table eql 0/65 0x40f50bad> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f50ddd> :action-handlers #<hash-table equal 0/65 0x40f50dfd> :major-modes (kotlin-mode) :activation-fn nil :priority -1 :server-id kotlin-ls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil) #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x40f514b5>) :test\? #f(compiled-function () #<bytecode 0x40f514c9>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 2/65 0x40f514d5> :request-handlers #<hash-table equal 1/65 0x40f515fd> :response-handlers #<hash-table eql 0/65 0x40f51a41> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x40f5161d> :action-handlers #<hash-table equal 0/65 0x40f5163d> :major-modes (hack-mode) :activation-fn nil :priority -1 :server-id hack :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil)))
      lsp--find-clients(python-mode "/Users/isolet/competitions/tags.py")
      lsp--try-project-root-workspaces(nil nil)
      lsp()
      (progn (lsp))
      (if (derived-mode-p (quote python-mode)) (progn (lsp)))
      python-lsp()
      run-hooks(hack-local-variables-hook)
      hack-local-variables-apply()
      hack-local-variables(no-mode)
      run-mode-hooks(python-mode-hook)
      python-mode()
      set-auto-mode-0(python-mode nil)
      set-auto-mode()
      normal-mode(t)
      after-find-file(nil nil t nil nil)
      revert-buffer--default(t nil)
      revert-buffer(t)
      funcall-interactively(revert-buffer t)
      call-interactively(revert-buffer nil nil)
      command-execute(revert-buffer)

My Emacs version is `GNU Emacs 26.2.90 (build 1, x86_64-apple-darwin18.6.0, Carbon Version 158 AppKit 1671.5) of 2019-03-22`.

**Comment by smallzhan** [comment]
Have a look at #38

**Comment by seagle0128** [comment]
According to #38, this can be closed.
