### ISSUE TITLE
Added PR with changes that makes lsp-python-ms work with the new lsp.el

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-python-ms#4]
Added preliminary changes in PR #2 and #3 that makes this package work with the new "lsp.el".

In order to make it more robust on windows I published my local server to a exe-file, using the command

`dotnet publish -c Release -r win10-x64`

I added a variable `lsp-python-ms-executable` that points to the exe-file. Is this variable is non-nil, the contents of the variable will be used as language server, otherwise the old functionality is used.

**Comment by andrew-christianson** [comment]
Awesome! I will merge #3 and add your note on executables to the README

**Comment by astenman** [comment]
Thank you! It was the first time I was submitting PRs to Github, so I wasn't sure that I did it right.

I still have a problem that I get an error from the language server (see below). But I do not have time right now to debug it. Perhaps towards the end of the week.

`<<<< mspyls:20748
{
  "jsonrpc": "2.0",
  "method": "python/languageServerStarted",
  "params": []
}
[MS Python language server started]
<<<< mspyls:20748
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///c%3A/Software/LoggerNDS/ndrstreamer.py",
    "diagnostics": []
  }
}
<<<< mspyls:20748
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32000,
    "message": "unknown document",
    "data": "   at Microsoft.Python.LanguageServer.Implementation.ProjectFiles.GetEntry(Uri documentUri, Boolean throwIfMissing) in C:\\Software\\python-language-server\\src\\LanguageServer\\Impl\\Implementation\\ProjectFiles.cs:line 53\r\n   at Microsoft.Python.LanguageServer.Implementation.Server.HierarchicalDocumentSymbol(DocumentSymbolParams params, CancellationToken cancellationToken) in C:\\Software\\python-language-server\\src\\LanguageServer\\Impl\\Implementation\\Server.WorkspaceSymbols.cs:line 63\r\n   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.DocumentSymbol(JToken token, CancellationToken cancellationToken) in C:\\Software\\python-language-server\\src\\LanguageServer\\Impl\\LanguageServer.cs:line 328"
  },
  "id": 2
}`

**Comment by seanfarley** [comment]
Looks like this can be closed now, fyi
