### ISSUE TITLE
File mode specification error: (error Cannot find Microsoft Python Language Server executable! It’s expected to be Microsoft.Python.LanguageServer)

### ISSUE THREAD

**Issue by patzhang** [emacs-lsp/lsp-python-ms#44]
After I upgraded the package with the new installation function (Setup MS PYLS automatically), I have the following error. 
```
Downloading Microsoft Python Language Server...
Contacting host: pvsc.blob.core.windows.net:443
Wrote /tmp/mspylsQCQTIi.zip
(Shell command succeeded with no output)
Downloaded Microsoft Python Language Server!
File mode specification error: (error Cannot find Microsoft Python Language Server executable! It’s expected to be Microsoft.Python.LanguageServer)
```
I can see the zip file has been downloaded and unzipped into `.emacs.d/mspyls` directory. However, the file `Microsoft.Python.LanguageServer` is not executable. This code [(chmod lsp-python-ms-executable #o755))](https://github.com/emacs-lsp/lsp-python-ms/blob/95f7d0d7b72afb1c898e206ba662812d21bcec71/lsp-python-ms.el#L140) did not work in my case.

Even I manually changed the file mode to `755`, it still always try to install ms pls again.

I am using Ubuntu 18.04, Emacs 26.2 and pipenv.

@yyoncho  @seagle0128  Any ideas?
Any help is highly appreciated. Thanks.

**Comment by seagle0128** [comment]
@patzhang What are the values of `lsp-python-ms-dir` and `lsp-python-ms-executable`? 

Please eval `(file-exists-p lsp-python-ms-executable)` in your env.

**Comment by patzhang** [comment]
Many thanks for your reply, @seagle0128.
`lsp-python-ms-dir` is nil.
`lsp-python-ms-executable` is `Microsoft.Python.LanguageServer`
`(file-exists-p lsp-python-ms-executable)` is nil.
I am not sure why the `lsp-python-ms-dir` is not configured properly with [this](https://github.com/emacs-lsp/lsp-python-ms/blob/95f7d0d7b72afb1c898e206ba662812d21bcec71/lsp-python-ms.el#L42).

I forgot to mention that I am using Spacemacs dev branch with the configuration like the follows:
```
 dotspacemacs-configuration-layers
   '(
     (lsp :variables
         company-lsp-cache-candidates 'auto
         lsp-ui-flycheck t
         )

     (python :variables
         python-backend 'lsp
         python-lsp-server 'mspyls
         )
)
```
I suspect this may be related to my previous installation with the manually compiled MS PLS. I will try a clean installation with my current Spacemacs configurations and see it helps.

**Comment by patzhang** [comment]
Just tried a clean installation of Spacemacs dev branch on mac OSX. The same error happens.
`lsp-python-ms-dir` is `/Users/myusername/.emacs.d/mspyls/`.
`lsp-python-ms-executable` is `Microsoft.Python.LanguageServer`
But `(file-exists-p lsp-python-ms-executable)` is `nil`.
Any ideas? 
Thanks.
```
pipenv --venv finished
Downloading Microsoft Python Language Server...
Contacting host: pvsc.blob.core.windows.net:443 [2 times]
Wrote /var/folders/6p/1zr8245s5yj9654h33q3tt20tr7z10/T/mspylsoK75tU.zip
(Shell command succeeded with no output)
Downloaded Microsoft Python Language Server!
File mode specification error: (error Cannot find Microsoft Python Language Server executable! It’s expected to be Microsoft.Python.LanguageServer)
"/Users/myusername/.emacs.d/mspyls/"
"Microsoft.Python.LanguageServer"
Quit
nil
pipenv --venv finished
Downloading Microsoft Python Language Server...
Contacting host: pvsc.blob.core.windows.net:443 [2 times]
Wrote /var/folders/6p/1zr8245s5yj9654h33q3tt20tr7z10/T/mspyls1ZWE6E.zip
(Shell command succeeded with no output)
Downloaded Microsoft Python Language Server!
File mode specification error: (error Cannot find Microsoft Python Language Server executable! It’s expected to be Microsoft.Python.LanguageServer)
```

**Comment by seagle0128** [comment]
I am not using spacemacs, but I believe it's a configuration issue. `lsp-python-ms-executable` should be `/Users/myusername/.emacs.d/mspyls/Microsoft.Python.LanguageServer`.

```elisp
(defvar lsp-python-ms-executable (concat lsp-python-ms-dir
                                         "Microsoft.Python.LanguageServer"
                                         (and (eq system-type 'windows-nt) ".exe"))
  "Path to Microsoft.Python.LanguageServer.exe.")
```

Try to set `lsp-python-ms-executable` manually.

Updated: https://github.com/syl20bnr/spacemacs/blob/d8defccf7ad9f18e4b0f3732ddb5f496ccede2f1/layers/%2Blang/python/packages.el#L435

Python layer should be updated.

**Comment by patzhang** [comment]
Good point. Thanks for pointing out the root cause. Seems like 
[(setq lsp-python-ms-executable "Microsoft.Python.LanguageServer"))))](https://github.com/syl20bnr/spacemacs/blob/d8defccf7ad9f18e4b0f3732ddb5f496ccede2f1/layers/%2Blang/python/packages.el#L439) overwrites `lsp-python-ms-executable`, because the non-automated installation has the executable in the path.

I temporarily set `lsp-python-ms-executable` and it works.
```
(lsp :variables
      lsp-python-ms-executable "~/.emacs.d/mspyls/Microsoft.Python.LanguageServer")
```
I will raise an issue for the python layer.
Thanks for your help, @seagle0128

**Comment by seagle0128** [comment]
Welcome, @patzhang !
It seems this can be closed now.
