### ISSUE TITLE
mspyls automatic download should timeout

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-python-ms#46]
In my workplace all the ports below 1024 are blocked. 
Since the automatic download request uses port 443, Emacs freezes on the initialization waiting the download operation to finish. 
Does a workaround exist to bypass this problem?

**Comment by seagle0128** [comment]
Can you use the proxy to download? mspyls is only able to be downloaded via https.

**Comment by innerout** [comment]
The easiest solution is to clone mspyls from git and build it to tell the truth.

**Comment by seagle0128** [comment]
It's true if you have trouble to download and installed dotnet core sdk.

**Comment by innerout** [comment]
Could the plugin ask if it should download from Microsoft or clone from git?

**Comment by seagle0128** [comment]
For better experience, the automatic downloading is recommended, like `lsp-java`. Of course, you can download manually or build it yourself.
