### ISSUE TITLE
Language Server is not downloading

### ISSUE THREAD

**Issue by lexxish** [emacs-lsp/lsp-python-ms#47]
Language server does not appear to be downloading. Even though the messages say "Downloaded Microsoft Python Language Server", mspyls directory is empty. I also mentioned this here https://github.com/syl20bnr/spacemacs/issues/12497 but it appears to be an lsp-python-ms issue.

```Contacting host: pvsc.blob.core.windows.net:443
Wrote c:/Users/lexxish/AppData/Local/Temp/mspylsbP3Ckn.zip
/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
Downloaded Microsoft Python Language Server!
File mode specification error: (error Cannot find Microsoft Python Language Server executable! It’s expected to be c:/Users/lexxish/.emacs.d/mspyls/Microsoft.Python.LanguageServer.exe)```

**Comment by lexxish** [comment]
The only way I have been able to get this working so far is to manually build:
```
git clone https://github.com/Microsoft/python-language-server.git
cd python-language-server/src/LanguageServer/Impl
dotnet publish --self-contained -r win10-x64 --configuration Release
```
  
And point to language server .exe in my .spacemacs file:
```
(python :variables
               python-backend 'lsp
               python-lsp-server 'mspyls
               lsp-python-ms-executable "~/.emacs.d/private/language-servers/python-language-server/output/obj/Microsoft.Python.LanguageServer/netcoreapp2.2/win10-x64/host")
```
I'm using the latest code in spacemacs develop and I made sure is has the updates from https://github.com/syl20bnr/spacemacs/issues/12497

**Comment by smallzhan** [comment]
According to your log, the server downloading finished, the file is in `c:/Users/lexxish/AppData/Local/Temp/mspylsbP3Ckn.zip`, 
seems uncompress zip file failed. 
```emacs-lisp 
(unzip-script (cond ((executable-find "unzip")
                               "bash -c 'mkdir -p %2$s && unzip -qq %1$s -d %2$s'")
```
since you are in windows, unzip-script should be `powershell ...`.
So, maybe you can move `unzip.exe` out of the $PATH temporarily and try again.

**Comment by seagle0128** [comment]
I agree with @smallzhan . I guess @lexxish is using cygwin or msys2, so bash.exe and unzip.exe are used to uncompress the zip package but failed. I can do some optimizations here.

**Comment by lexxish** [comment]
Could it ignore path so it's self contained and compatible with cygwin or other environments?

**Comment by seagle0128** [comment]
From Windows Vista, `powershell` is built-in, and able to handle zip package now. Moreover it's not easy to be compatible with cygwin and other environments. I am not using Windows in daily work so lack of tests there. I think new version is fine for Windows. Please let me know if you still have issues.
