### ISSUE TITLE
Invalid function "python/languageServerStarted" with new lsp-register-client

### ISSUE THREAD

**Issue by samspills** [emacs-lsp/lsp-python-ms#5]
I'm trying to get this working with a new version of `lsp-mode` (`20181217.630`, using the new `lsp-register-client` functionality) and it is failing to run `lsp-python-enable` with the title error.  I'm on Spacemacs v0.200.13, emacs 26.1. 

I've tried running in debug mode with only the `lsp-mode` and `lsp-python-ms` packages (none of the spacemacs config included), and if I go to a python file and manually start `lsp`, the `mspyls` buffer is created but the server doesn't start because the executable command seems to be malformed. The exact error is: `No executable found matching command "dotnet-Microsoft.Python.LanguageServer.dll"`

The relevant section of my config looks like so:

```lisp
(use-package lsp-mode
    :ensure t
    :config
    (require 'lsp-clients)
    ;; change nil to 't to enable logging of packets between emacs and the LS
    ;; this was invaluable for debugging communication with the MS Python Language Server
    ;; and comparing this with what vs.code is doing
    (setq lsp-print-io t))
(use-package lsp-python-ms
    :ensure nil
    :hook (python-mode . 'lsp-python-enable)
    :config
    ;; for dev build of language server
    (setq lsp-python-ms-dir
          (expand-file-name "/usr/local/etc/python-language-server/output/bin/Release/")))
```

Also full disclosure: In my attempts to debug and play around with different versions of lsp-mode I have further broken things, and now I'm getting the following error: `lsp-python-ms.elc failed to define function lsp-python-enable`. So I'll try to keep looking into this and provide any other info that might help, but also I'm going to try to fix the problems that I created 😅

**Comment by andrew-christianson** [comment]
@samspills #6 resolves this for me, please let me know if you're still seeing issues

**Comment by samspills** [comment]
Thanks for the heads up @andrew-christianson! I'll take a look tonight and let you know

**Comment by seanfarley** [comment]
This can also be closed now :-)
