### ISSUE TITLE
LSP sends response to the wrong process when we have nested projects

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-python-ms#59]
My project has a submodule python project. The first time I open a python file in the submodule project, msplys works. But if I open another python file in other folder inside the submodule. It cannot resolve any mspyls function.

It seems like responses have been sent to the wrong mspyls process. In my case, I trigger some event in submodule's python buffer, and it returns response to root project's mspyls process. You can tell from the log I attached.

<details>
  <summary>mspyls: Lsp log to submodule</summary>
  [Trace - 05:14:24 PM] Sending request 'textDocument/definition - (5)'.
Params: {
  "textDocument": {
    "uri": "file:///home/ztlevi/XXX/AAA.py"
  },
  "position": {
    "line": 11,
    "character": 60
  }
}

[Trace - 05:14:24 PM] Received notification 'telemetry/event'.
Params: {
  "Measurements": {
    "elapsedMs": 1.8551000000000002
  },
  "Properties": {
    "plsVersion": "0.4.24.0",
    "method": "textDocument/definition"
  },
  "EventName": "python_language_server/rpc.request"
}

[Trace - 05:14:24 PM] Received response 'textDocument/definition - (5)' in 11ms.
Result: [
  {
    "range": {
      "end": {
        "character": 14,
        "line": 21
      },
      "start": {
        "character": 4,
        "line": 21
      }
    },
    "uri": "file:///home/ztlevi/XXX/AAA.py"
  }
]

[Trace - 05:14:27 PM] Sending request 'textDocument/signatureHelp - (6)'.
Params: {
  "textDocument": {
    "uri": "file:///home/ztlevi/XXX/BBB.py"
  },
  "position": {
    "line": 11,
    "character": 60
  }
}

[Trace - 05:14:27 PM] Received notification 'telemetry/event'.
Params: {
  "Measurements": {
    "elapsedMs": 14.3316
  },
  "Properties": {
    "plsVersion": "0.4.24.0",
    "method": "textDocument/signatureHelp"
  },
  "EventName": "python_language_server/rpc.request"
}

[Trace - 05:14:27 PM] Received response 'textDocument/signatureHelp - (6)' in 51ms.
Result: null
</details>

<details>
  <summary>mspyls: Lsp log to root project</summary>

[Trace - 05:44:48 PM] Sending request 'textDocument/definition - (31)'.
Params: {
  "textDocument": {
    "uri": "file:///home/ztlevi/YYY/CCC.py"
  },
  "position": {
    "line": 11,
    "character": 61
  }
}
</details>

### some tests with other language server
- Tested submodule project with pyls, it worked out without any issue.
- Tested submodule project with anaconda-mode, it works as well.
- Tested with vscode with mspyls enable, works.

I'm not fully understand my error and I fail to reproduce the error from a scratch project. But this is all I got and I need some help!

**Comment by yyoncho** [comment]
@ztlevi can you provide a project+steps to reproduce the issue with?

**Comment by ztlevi** [comment]
@yyoncho I tried but failed.

And the project has the issue is my company's project and of course I couldn't upload it. 

But we can start from the lsp log. Apparently, there are two logs tied with different project roots generated. I tried to debug `lsp-python-ms--workspace-root` but it should always returns my submodule's project root.

```
(defun lsp-python-ms--workspace-root ()
  "Get the path of the root of the current workspace.

Use `lsp-workspace-root', which is pressent in the \"new\"
lsp-mode and works when there's an active session.  Next try ffip
or projectile, or just return `default-directory'."
  (cond
   ((and (fboundp #'lsp-workspace-root) (lsp-workspace-root)))
   ((fboundp #'ffip-get-project-root-directory) (ffip-get-project-root-directory))
   ((fboundp #'projectile-project-root) (projectile-project-root))
   (t default-directory)))
```

Interestingly, `projectile-project-root` will return my root project's path. But it's not being called in `lsp-python-ms--workspace-root`. Maybe it's something related with lsp-mode. While, another fact is, I can use lsp-mode with pyls perfectly in this project without any issue...

**Comment by ztlevi** [comment]
@yyoncho I eventually found the problem is caused by `(add-to-list 'projectile-project-root-files-bottom-up ".ccls-root")`. Once I remove the `.ccls-root` file, mspyls is working again!

Can you try to explain why would the change of projectile root strategy would create a different mspyls process?
