### ISSUE TITLE
not all available completion candidates are shown

### ISSUE THREAD

**Issue by kirk86** [emacs-lsp/lsp-python-ms#64]
I don't see all completion candidates when I use numpy. For comparison here's what I see in the bufffer
![image](https://user-images.githubusercontent.com/2902390/66791163-f1eb5300-eeea-11e9-9112-e93fa0ced8f8.png)

As you can see the `np.exp` function is nowhere shown in the completions, and for comparison heres what I get on python REPL
![image](https://user-images.githubusercontent.com/2902390/66791201-17785c80-eeeb-11e9-8301-6287076fcd7f.png)

**Comment by seagle0128** [comment]
I tested in VSCode, the same completion candidates were displayed. Please check.

That means the issue exists in the upstream. Please report to https://github.com/Microsoft/python-language-server.

**Comment by seagle0128** [comment]
Close it due to it's an issue of upstream.

Please check https://github.com/microsoft/python-language-server/issues/1414.
