### ISSUE TITLE
[question] How to disable the cache?

### ISSUE THREAD

**Issue by kirk86** [emacs-lsp/lsp-python-ms#66]
Hi I was wondering if there's any command to disable the cache as shown [here](https://github.com/microsoft/python-language-server/wiki/Module-caching). I've greped the mspyls folder but couldn't find any text containing "python.analysis.cachingLevel": "System". Is there such an option through `lsp-python-ms` ?

**Comment by seagle0128** [comment]
There is no such option so far. But you can try this:

```elisp
(lsp-register-custom-settings
 '(("python.analysis.cachingLevel" "None"))
```
