### ISSUE TITLE
Automatic install does not work on Windows 10

### ISSUE THREAD

**Issue by surgeboris** [emacs-lsp/lsp-python-ms#69]
On Windows 10 automatic install downloads the nupkg, logs `Extracting Microsoft Python Language Server...done` and exits. When I check `~/.emacs.d/mspyls` it's empty.

I guess that error happens during unzipping nupkg, and this error does not get reported back into Emacs.

On my machine the resulting Powershell command to extract `mspyls` looks like that:
```
powershell -noprofile -noninteractive -nologo -ex bypass Expand-Archive -path '~/Desktop/Python-Language-Server-win-x64.0.4.71.nupkg' -dest '~/.emacs.d/mspyls/'
```

When I try to run it directly in Powershell prompt I get the following:
```
Expand-Archive : .nupkg is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:1
+ Expand-Archive -path ~/Desktop/Python-Language-Server-win-x64.0.4.71. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.nupkg:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
```

I'm not sure how it should be fixed since I'm not proficient with Powershell, but I guess we're supposed to add some flag to override file extension check...

**Comment by yyoncho** [comment]
Or save it with zip extension. Can you verify that this works by remaining the file and reruning the command?

**Comment by surgeboris** [comment]
> Can you verify that this works by remaining the file and reruning the command?

I have verified it: using .zip extension instead of .nupkg solves the problem (Powershell command works).

**Comment by seagle0128** [comment]
Actually the downloaded package is save as `.zip` file. Refer to https://github.com/emacs-lsp/lsp-python-ms/blob/master/lsp-python-ms.el#L165.

I don't think the failure is caused by invalid subfix.

UPDATE: the args of powershell are exactly same as `dap-utils`.

**Comment by seagle0128** [comment]
I drop a commit to show better messages after extracting the package. Please update to check.

**Comment by surgeboris** [comment]
@seagle0128 Oh, you're right. I jumped to my conclusion too quickly. Sorry about that.

My problem has nothing to do with the extension of the temp file. I checked your commit and investigated my problem further:
```
Downloading Microsoft Python Language Server...done
Extracting Microsoft Python Language Server...
Quit
Failed to extract Microsoft Python Language Server: 0
```
I've checked the *actual* temp-file (this time I double-checked that this is it; something like `~/AppData/Local/Temp/mspylsQM7Rod.zip`), and manually launched powershell command on it. Command immediately silently exited, no actual files where created in `~/.emacs.d/mspyls/`.

I downloaded `Python-Language-Server-win-x64.0.4.71.nupkg` file through the browser, saved it as *.zip file, and executed powershell command on it: there was a progress bar displayed a Powershell and `~/.emacs.d/mspyls` got populated with files.

I compared filesizes of the temp-file and manually downloaded file: temp file is 117Kb bigger than manually downloaded one.

Apparently something goes wrong when we're writing fetched http object buffer onto the disk. Initially I thought that we're writing http-headers as file content, but we (apparently) don't: `(re-search-forward "\r?\n\r?\n")` works properly on fetched http object buffer.

I opened both temp-file and manually downloaded file side-by-side in `hexl-mode`: starting and ending bytes are the same, so extra 117Kb are somewhere in the middle of the file. I have no idea what might cause that difference...

**Comment by surgeboris** [comment]
Found it!

To have a proper binary written we supposed to set a `coding-system-for-write` variable to `'binary` before writing (usage of `let` is recommended by variable documentation):
```
(let ((coding-system-for-write 'binary))
  (write-region (point) (point-max) temp-file))
```

With that change extracting mspyls out of the temp-file works correctly on my machine.

**Comment by seagle0128** [comment]
@surgeboris Thank you! It's safer to save the temp buffer, whatever it's set to any coding system in users' envs.
