### ISSUE TITLE
Can we make the parse-dot-env optional?

### ISSUE THREAD

**Issue by fangherk** [emacs-lsp/lsp-python-ms#70]
I just ran a package update in Spacemacs and found that the function `(lsp-python-ms--parse-dot-env workspace-root)` throws an error in this commit https://github.com/emacs-lsp/lsp-python-ms/commit/6151d9f47f7c9557a7fa8d7228425f5524a8fd21. It throws an error for not having a `.env` file in a custom `.venv`, so I manually updated the `lsp-python-ms.el` to the prior commit. Can this parsing be optional?

**Comment by seagle0128** [comment]
@astenman Can you please take a look?

**Comment by astenman** [comment]
@seagle0128 Yes I will fix this.

@fangherk Can you elaborate on the error. Do you have a .env file in the project root? What does this file contain? Maybe you can provide me with a stack trace ...

**Comment by fangherk** [comment]
I don't use a .env file in the project root. I rely on`pyvenv-activate` to detect the virtualenv in use of the repository, since I am currently working with a  monolith with multiple virtualenvs for different deploys. Thus, the root isn't actually the head of the repo. 

Whenever I run `lsp` and import the root interactively,  `(lsp-python-ms--parse-dot-env workspace-root)` throws a `(lsp-python-ms--parse-dot-env workspace-root)`.  

Calling the line `(setq lsp-python-ms-parse-dot-env-enabled nil)` solves my issue.

**Comment by seagle0128** [comment]
So can this be closed now? @fangherk
