### ISSUE TITLE
Does this support snippets?

### ISSUE THREAD

**Issue by jsigman** [emacs-lsp/lsp-python-ms#78]
I see that `lsp-mode` supports snippets, but only if the language server does as well. Does the microsoft vs code python language server support snippets?

**Comment by seagle0128** [comment]
Use `lsp-describe-session` to check the capabilities.

**Comment by jsigman** [comment]
Says nope

**Comment by jsigman** [comment]
I should ask more precisely... What does it take to make this mode support snippets? I can't seem to find any resources on this online

**Comment by seagle0128** [comment]
See  `lsp-enable-snippe`, with `yasnippet` package.
