### ISSUE TITLE
No LSP server for python-mode

### ISSUE THREAD

**Issue by Pilgrim1379** [emacs-lsp/lsp-python-ms#8]
I've followed the instructions to the letter I believe but when I open a simple python file that contains a print statement, I get the message in the mini-buffer `LSP :: No LSP server for python-mode`. Apart from the installation instructions provided, should I do something else? What am I missing?

**Comment by andrew-christianson** [comment]
Can you share your configuration of the client?

Note that the use-package block in the README is just an example, and assumes the package is already on your load-path. Once I get this in MELPA I’ll be able to provide a more robust configuration example.

**Comment by yyoncho** [comment]
Just want to mention that you will get `LSP :: No LSP server for python-mode` if `(find-executable XXX)` where XXX is the first string from the generated command.

**Comment by Pilgrim1379** [comment]
Thanks for your responses. The following are all the settings I have in my config relating to lsp and python:

**init-python.el**

```
(use-package lsp-python-ms
  :load-path "site-lisp/lsp-python-ms"
  :ensure nil
  :hook (python-mode . lsp)
  :config
  ;; for dev build of language server
  (setq lsp-python-ms-dir
        (expand-file-name "~/Github/python-language-server/output/bin/Release/"))
  ;; for executable of language server
  (setq lsp-python-ms-executable
        "~/Github/python-language-server/output/bin/Release/osx-x64/publish/Microsoft.Python.LanguageServer"))


(provide 'init-python)
```


**init-lsp-mode.el**

```
(use-package lsp-mode
  :ensure t
  :commands lsp
  :hook
  (elixir-mode . lsp)
  :init
  (setq lsp-prefer-flymake nil)
  (add-to-list 'exec-path "/Users/napo/Github/elixir-ls/release")
  :init
  (add-hook 'prog-major-mode #'lsp-prog-major-mode-enable))

(use-package lsp-ui
  :ensure t
  :commands lsp-ui-mode)

(provide 'init-lsp-mode)
```

**company-lsp**

```
(use-package company-lsp
  :ensure t
  :init
  (push 'company-lsp company-backends))

```

I have lsp-python-ms cloned to "site-lisp/lsp-python-ms". 

@yyoncho I don't quite understand what follow up action I should take regarding your comment 

> Just want to mention that you will get LSP :: No LSP server for python-mode if (find-executable XXX) where XXX is the first string from the generated command.

**Comment by andrew-christianson** [comment]
@thepreacher thanks for the details.  I think it should work for if you add a `:demand` to the use-package specification for `lsp-python-ms`. Otherwise use-package automatically defers loading the package, and we never call something that prompts the package to be autoloader, so `lsp-register-client` is never called.

**Comment by Pilgrim1379** [comment]
@andrew-christianson thanks I made the suggested change and it works now 👍. Great additional explanation as well. I learned something from it.
