### ISSUE TITLE
Use-package installation instructions not working

### ISSUE THREAD

**Issue by shaneikennedy** [emacs-lsp/lsp-python-ms#81]
I've added the `use-package` config example from the README but get the following error on startup:

`Error (use-package): lsp-python-ms/:catch: Symbol’s value as variable is void: lsp-server-install-dir`

**Comment by yyoncho** [comment]
Install latest version of lsp-mode

**Comment by hartzell** [comment]
I'm also seeing this problem, using the current master (commit: 83ef84d)

`lsp-server-install-dir` is only mentioned once, where it's used to define a value for `lsp-python-ms-dir`:

```
(alice)[17:19:31]lsp-python-ms>>rg lsp-server-install-dir
lsp-python-ms.el
51:(defcustom lsp-python-ms-dir (f-join lsp-server-install-dir "mspyls/")
(alice)[17:19:50]lsp-python-ms>>git status
```

I suspect I'm missing something obvious....

Help?

**Comment by hartzell** [comment]
ps.  It works if I check out the `v0.5.0` tag.

**Comment by seagle0128** [comment]
@hartzell Please upgrade `lsp-mode`.

**Comment by hartzell** [comment]
**My apologies**, I wasn't reading carefully, I read [the words in the comment above](https://github.com/emacs-lsp/lsp-python-ms/issues/81#issuecomment-571557523) and/but my brain took it to be "use the latest lsp-python-ms".

Thanks!
