### ISSUE TITLE
Unable to run lsp-python-ms due to error

### ISSUE THREAD

**Issue by CSRaghunandan** [emacs-lsp/lsp-python-ms#83]
Whenever I open a file, I get an error saying `Error running timer: (error "No workspace could handle textDocument/codeLens")`

Sometimes `lsp` works fine, whereas most of the time it does not. Any idea how  I can fix this problem?

I have used the similar use-package conifg as whats shown in readme to initialize the `lsp` configuration for emacs

**Comment by seagle0128** [comment]
@yyoncho Can you take look at this? The error is reported by `lsp--send-request-async`.

**Comment by yyoncho** [comment]
Do you have lsp-lens-auto-enable set to t?

**Comment by CSRaghunandan** [comment]
@yyoncho its value is `nil`

I haven't set this variable anywhere

**Comment by yyoncho** [comment]
Can you do `M-x debug-on-entry RET lsp-lens-mode` and paste the callstack here?

**Comment by yyoncho** [comment]
Solved here: https://www.reddit.com/r/emacs/comments/eqh3x2/unable_to_get_microsoft_pythonlanguageserver_to/
