### ISSUE TITLE
Issue: Jump to module definition in Python2 instead of Python3

### ISSUE THREAD

**Issue by ianyepan** [emacs-lsp/lsp-python-ms#84]
I'm using lsp-python-ms mainly because this server allows me to jump to more library function definitions than pyls can provide. But lately, I found out that lsp-python-ms jumps to the definition in the python2.7 library instead of the python3.7 library on my system.
Take the built-in curses module for example, considering the following code
```python
import curses
s = curses.initscr()
```
When I invoke xref on `initscr()` to go to its definition, it takes me to `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/__init__.py` instead of `/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/init.py`. FYI, using the same go-to-denition in Visual Studio Code takes me to the python3 version of `__init__.py`.
I'm wondering if there is a setting that configures the default python interpreter to be python3 instead of python2.

**Comment by seagle0128** [comment]
Please check `lsp-python-ms-python-executable-cmd`.

**Comment by ianyepan** [comment]
> Please check lsp-python-ms-python-executable-cmd

Thanks, now it's working perfectly!
