### ISSUE TITLE
What to do about melpa?

### ISSUE THREAD

**Issue by seanfarley** [emacs-lsp/lsp-python-ms#9]
It seems that the [ms-python](https://github.com/xhcoding/ms-python) package beat this one to the punch for being listed on melpa.

What should we do? Merge the two? Just list both? 🤔

**Comment by seanfarley** [comment]
Since @cpbotha originally wrote the code, I wonder if he has any thoughts on the matter?

**Comment by cpbotha** [comment]
Looking at the commit log, @xhcoding started his package on November 23 with code from my blog post. (I just noticed his readme does link back to my blog post, quite prominently. :)

Anyways, @andrew-christianson started *this* package on November 27, a few days later. We did not see that there already was a package, else we could have joined forces.

The most logical thing to do would be to compare functionality, and ensure that the union of the two packages is on melpa so that Emacs users get the best solution available. If @xhcoding is a responsive maintainer, I'm sure that should not be a problem.

**Comment by cormacc** [comment]
The ms-python package on melpa appears to be windows-only (based on a quick scan of the source, there seems to be a hard-coded dll expectation), whereas this also works on linux (and I'd imagine probably OSx too?).

Kudos on spotting/fixing the filter / nil string bug quickly by the way -- I was just about to submit a PR :)

**Comment by cpbotha** [comment]
It's not Windows-only. dotnet core builds DLLs on all platforms. :)

Its major issue is that it does not yet support the new LSP API, which this package does. I was hoping @xhcoding would pop in here for chat so we could make plans.

**Comment by cormacc** [comment]
Ah, that I didn't know (clearly :) )

Anyway, I've added this to the spacemacs python layer and submitted a PR. Just pulling the package from git for now.

See https://github.com/syl20bnr/spacemacs/pull/11913

**Comment by xhcoding** [comment]
I'm sorry for my hasty behavior. 
I think merging two packages is a good solution. Maybe I can transfer my package here and update the recipe on MELPA, or we discuss other solutions together.

**Comment by cpbotha** [comment]
Hi there @xhcoding ! It's great that you want us to join efforts.

Because most of the activity seems to have congregated on this repo, my suggestion is indeed that we merge @xhcoding 's work into this repo, and then update the melpa.

@andrew-christianson and the rest, what do you think?

**Comment by andrew-christianson** [comment]
Sounds good to me!

@xhcoding no need to apologize!  I'll look through ms-python to flag anything we should merge here, and happily accept any PRs from you for those or other enhancements.  

I'll also PR this to MELPA, under the current package name, if that works for everyone, as it's already linked as such from the lsp-mode README, and from @cormacc's Spacemacs PR as such.

@cpbotha I neglected to include a LICENSE when I created this repo, as I didn't see if you explicitly released (any/every)thing on your blog under a specific license.  Are you ok with releasing this under GPL?

**Comment by cpbotha** [comment]
@andrew-christianson GPL sounds fine to me. (for other OSS I usually do BSD, but it looks like for Emacs packages GPL is the norm?)

**Comment by andrew-christianson** [comment]
I'll stick with that then :)

e: by which I mean 3-clause BSD.  It's compatible with GPL per FSF, so it should be fine for MELPA

**Comment by yyoncho** [comment]
2 more options:

1. I can create a project under emacs-lsp organization and give commit rights to whoever is interested to support the extension.
2. Move the code in lsp-clients.el.

**Comment by josteink** [comment]
Emacs has recently started flagging packages which are not GPL licensed as “incompatible“. 

True or not, using anything not GPL might make life more cumbersome for users, so I advice going for GPL to cause a minimum of friction.

**Comment by cpbotha** [comment]
I'm happy with whatever license gets it onto MELPA and into Emacs users' configs. :)

**Comment by rememberYou** [comment]
Thanks for creating this package, it will simplify the life of more than one developer. Do you have any idea when the package will be on MELPA?

**Comment by andrew-christianson** [comment]
@rememberYou mepla PR: melpa: melpa/melpa#6027

**Comment by andrew-christianson** [comment]
package is in melpa (thanks @purcell!) @xhcoding I'll fold in the changes from your most recent commit (along with Steve's suggestions for polish #23), and leave it to you to PR removal of ms-python to mepla 

@yyoncho would it still be possible to shift this repo over to the emacs-lsp organization, and add @xhcoding @cpbotha and myself as maintainers?

**Comment by yyoncho** [comment]
@andrew-christianson yes, sounds good to me. Not sure how to do that. I guess one of the options is to transfer the repo ownership to me and then I will move it to the organization. If we do so the old links will still work and redirect to the new location.

**Comment by josteink** [comment]
> would it still be possible to shift this repo over to the emacs-lsp organization

Doing this is really simply. As the repo-owner, just use the transfer ownership function in the repo settings. I've done so myself for a few packages in the past (to other organizations).

Doing so also automatically creates a redirect for all "old" links to the old repo. All in all it's a no-hastle process which works as intended and does all the right things.

Obviously, once transferred, someone with the proper admin-rights for the organization needs to re-add you as a contributor/admin for to either the organization, repo or both (depending on what you guys want), but it shouldn't be a big job.

**Comment by purcell** [comment]
Thanks for organising this, folks! Transferring the repo like this would ensure the MELPA recipe continues to work fine. After the transfer we'd generally prefer to update the recipe to point at the new location for consistency.

**Comment by andrew-christianson** [comment]
@josteink ah, I didn't know about that feature.  Looks like it will do everything we need!

@yyoncho trying to transfer this to emacs-lsp org now.

edit: transfer failed as I don't have permissions to create repos in emacs-lsp.  @yyoncho could you add me to that org & grant create permission?

**Comment by yyoncho** [comment]
@andrew-christianson I just sent you an invite.

**Comment by andrew-christianson** [comment]
@yyoncho thanks and done!

**Comment by purcell** [comment]
MELPA recipe updated correspondingly. Thanks all!
