### ISSUE TITLE
Scope of a project/workspace?

### ISSUE THREAD

**Issue by haoyuan80s** [emacs-lsp/lsp-python-ms#99]
My autocompletion has very long setup time. As in the FAQ, I think it is due to:
"The folder may have huge folders and files, and the server takes a long time to index them. So please DO NOT put huge files in the project/workspace folder."

How to define the scope of a project/workspace?

Another question, how to switch between pyls and mspyls?

**Comment by seagle0128** [comment]
>How to define the scope of a project/workspace?

It depends on the CPU performance. You can try configure `lsp-python-ms-extra-paths` and other options  in `dir-locals`.

>Another question, how to switch between pyls and mspyls?

Not loading `lsp-python-ms` or change the priority of lsp clients.

**Comment by haoyuan80s** [comment]
Thanks! It seems to have a slower setup time, but faster than pyls after the setup.

**Comment by seagle0128** [comment]
Good to know it works. Closing it.
